# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da0b00d5a6571b955aa4f0857859cd2ab512d83d32b6e640c70e8861c22cbdeee9805294e790ebecaad20f7a943f256beaa925f12b2d847dbcbdb6e315032a63

test:
  secret_key_base: 027a004d076707af36b766330cf7f4ff207e44d94cd47fb653b593ef9dcff0dacc43a64e2bdedfad6c2372878f0c57de8dc45712016fa95fa55e559c29468675

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
